# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
    - language: python
      sudo: false
      python:
        - 2.7
        - 3.6
      install:
        - pip install docopt
        - pip install future
        - pip install psutil
      script:
        - python adb-enhanced/setup.py install

    # https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
    # https://stackoverflow.com/a/28751112/434196
    - language: android
      sudo: required  # For pip installation, otherwise, pip install fails.
      env:
        global:
        - ANDROID_API_LEVEL=26
        - ANDROID_BUILD_TOOLS_VERSION=26.0.1
        - ANDROID_EMU_API_LEVEL=22
        - ANDROID_ABI=armeabi-v7a
        - QEMU_AUDIO_DRV=none # Remove audio
        - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
      android:
        components:
          - tools
          - platform-tools
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL
          - android-$ANDROID_EMU_API_LEVEL
          # Specify at least one system image
          - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
      before_script:
        # Python setup
        - sudo pip install docopt
        - sudo pip install future
        - sudo pip install psutil
        # Android setup
        - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
        - emulator -avd test -no-window &
        - android-wait-for-emulator
      script:
        - python adbe.py app-signature com.android.phone -v
        - python adbe.py app-info com.android.phone -v
